server:
  hostname: mylabs.ru
  servlet:
    context-path: /api/dev

spring:
  datasource:
    username: root
    password: rootroot
    url: jdbc:mariadb://185.182.111.172:3306/mylabs
    driver-class-name: org.mariadb.jdbc.Driver
  mail:
    protocol: smtp
    username: MyLabsProgramming@gmail.com
    password: zezpwtvbqlfjyxtl
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true