server:
  hostname: my-labs.ru
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: root
    password: rootroot
    url: jdbc:mariadb://185.182.111.172:3306/mylabs
    driver-class-name: org.mariadb.jdbc.Driver
  mail:
    protocol: smtp
    username: MyLabsProgramming@gmail.com
    password: zezpwtvbqlfjyxtl
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+3
        ejb:
          interceptor: ru.mylabs.mylabsbackend.utils.TaskFilesInterceptor
        ddl-auto: update
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false